{"variants":[{"paths":["\/documentation\/adapty\/adaptyerror\/errorcode-swift.enum\/networkfailed"],"traits":[{"interfaceLanguage":"swift"}]}],"primaryContentSections":[{"declarations":[{"tokens":[{"kind":"keyword","text":"case"},{"kind":"text","text":" "},{"kind":"identifier","text":"networkFailed"}],"languages":["swift"],"platforms":["iOS"]}],"kind":"declarations"}],"schemaVersion":{"patch":0,"minor":3,"major":0},"hierarchy":{"paths":[["doc:\/\/Adapty\/documentation\/Adapty","doc:\/\/Adapty\/documentation\/Adapty\/AdaptyError","doc:\/\/Adapty\/documentation\/Adapty\/AdaptyError\/ErrorCode-swift.enum"]]},"metadata":{"roleHeading":"Case","role":"symbol","fragments":[{"text":"case","kind":"keyword"},{"text":" ","kind":"text"},{"kind":"identifier","text":"networkFailed"}],"modules":[{"name":"Adapty"}],"externalID":"s:6Adapty0A5ErrorV0B4CodeO13networkFailedyA2EmF","symbolKind":"case","title":"AdaptyError.ErrorCode.networkFailed"},"identifier":{"url":"doc:\/\/Adapty\/documentation\/Adapty\/AdaptyError\/ErrorCode-swift.enum\/networkFailed","interfaceLanguage":"swift"},"sections":[],"kind":"symbol","references":{"doc://Adapty/documentation/Adapty/AdaptyError/ErrorCode-swift.enum":{"title":"AdaptyError.ErrorCode","identifier":"doc:\/\/Adapty\/documentation\/Adapty\/AdaptyError\/ErrorCode-swift.enum","url":"\/documentation\/adapty\/adaptyerror\/errorcode-swift.enum","type":"topic","role":"symbol","navigatorTitle":[{"kind":"identifier","text":"ErrorCode"}],"kind":"symbol","fragments":[{"text":"enum","kind":"keyword"},{"text":" ","kind":"text"},{"text":"ErrorCode","kind":"identifier"}],"abstract":[]},"doc://Adapty/documentation/Adapty/AdaptyError/ErrorCode-swift.enum/networkFailed":{"type":"topic","role":"symbol","abstract":[],"url":"\/documentation\/adapty\/adaptyerror\/errorcode-swift.enum\/networkfailed","title":"AdaptyError.ErrorCode.networkFailed","fragments":[{"kind":"keyword","text":"case"},{"kind":"text","text":" "},{"text":"networkFailed","kind":"identifier"}],"identifier":"doc:\/\/Adapty\/documentation\/Adapty\/AdaptyError\/ErrorCode-swift.enum\/networkFailed","kind":"symbol"},"doc://Adapty/documentation/Adapty":{"identifier":"doc:\/\/Adapty\/documentation\/Adapty","url":"\/documentation\/adapty","type":"topic","title":"Adapty","kind":"symbol","role":"collection","abstract":[]},"doc://Adapty/documentation/Adapty/AdaptyError":{"title":"AdaptyError","identifier":"doc:\/\/Adapty\/documentation\/Adapty\/AdaptyError","url":"\/documentation\/adapty\/adaptyerror","type":"topic","role":"symbol","navigatorTitle":[{"kind":"identifier","text":"AdaptyError"}],"kind":"symbol","fragments":[{"text":"struct","kind":"keyword"},{"text":" ","kind":"text"},{"kind":"identifier","text":"AdaptyError"}],"abstract":[]}}}